services:
  db:
    image: postgres:16
    container_name: vgsales_db
    environment:
      POSTGRES_DB: vgsales_api
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: verysafepassword
    ports:
      - "5432:5432"
    volumes:
      - vgsales_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d vgsales_api"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: vgsales_api_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:verysafepassword@db:5432/vgsales_api
      JWT_SECRET_KEY: /6G1W,mO\M`zu1;Ww2£~rQ3b;_W%Vv\D;z-7X.Q£HG99m\C-=j
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  vgsales_pgdata: