"""
Main FastAPI application entry point.

This file defines the FastAPI app instance and registers routers for the
API. It also exposes basic health and database connectivity endpoints.

Swagger/OpenAPI metadata is defined here (title, version, tags, contact)
to keep the autogenerated documentation professional and easy to read.
"""

from fastapi import FastAPI
from sqlalchemy import text

from app.db import engine
from app.api.publishers import router as publishers_router
from app.api.catalogue import router as catalogue_router


# Human-friendly grouping + descriptions in Swagger UI
openapi_tags = [
    {
        "name": "health",
        "description": "Service readiness and database connectivity checks.",
    },
    {
        "name": "publishers",
        "description": "Publisher catalogue and publisher-specific game listings.",
    },
    {
        "name": "catalogue",
        "description": "Reference data (genres, platforms) derived from the dataset.",
    },
]


app = FastAPI(
    title="Game Publisher Intelligence API",
    version="0.1.0",
    description=(
        "An analytics-focused REST API built on the *Video Game Sales* dataset.\n\n"
        "**Key idea:** dataset tables are read-only; user-created resources (e.g., dashboards) "
        "provide the required CRUD layer.\n\n"
        "This API exposes catalogue endpoints and analytical endpoints designed for aggregation "
        "and derived metrics (publisher hit rate, efficiency, regional bias, momentum)."
    ),
    openapi_tags=openapi_tags,
    contact={
        "name": "Matthew Toon",
        "email": "sc22mt@leeds.ac.uk",
    },
)


@app.get(
    "/health",
    tags=["health"],
    summary="Health check",
    description="Confirms the API service is running (does not test database connectivity).",
)
def health():
    return {"status": "ok"}


@app.get(
    "/db-check",
    tags=["health"],
    summary="Database connectivity check",
    description="Executes a minimal `SELECT 1` query to confirm PostgreSQL connectivity.",
)
def db_check():
    with engine.connect() as conn:
        result = conn.execute(text("SELECT 1")).scalar_one()
    return {"database": "connected", "test_query": result}


# Register API routers
app.include_router(publishers_router)
app.include_router(catalogue_router)